name: Deploy Portfolio React App to Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      
    - name: Install Dependencies
      run: npm install
      
    - name: Build Production Version
      run: npm run build
      
    - name: Build Docker Image
      run: |
        docker build -t yourusername/portfolio-react-app:cd7a8fce2efd609df1eebffece3667a1e0c36742 .
        docker tag yourusername/portfolio-react-app:cd7a8fce2efd609df1eebffece3667a1e0c36742 yourusername/portfolio-react-app:latest
        
    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Push Docker Image
      run: |
        docker push yourusername/portfolio-react-app:${{ github.sha }}
        docker push yourusername/portfolio-react-app:latest

